### ISSUE TITLE
Constructor Name Comparison Fails for Minified Builds

### ISSUE THREAD

**Issue by rcollette** [peferron/chai-angular#2]
We test against our minified as well as non-minified builds.   The Resource constructor for our minified build becomes `$e(){}` so the constructor comparison fails (line 71)

**Comment by peferron** [comment]
Thanks for reporting this issue! It should be fixed in v2.0.0, published on npm just now.

The `Resource` constructor check has been completely removed. There was no good way to keep it in:
- Comparing by name doesn't survive minification (as you found out);
- Comparing by reference doesn't work because `angular-resource` doesn't always reuse the same `Resource` constructor;
- Comparing `constructor.toString()` or verifying that the object has special properties like `$promise` or `$resolved` is likely to be fragile.

Overall it doesn't seem very useful to verify that the object is a `Resource` anyway. We typically just want to verify that it contains the data it's supposed to.

**Comment by rcollette** [comment]
Awesome.. Thanks for the quick turnaround.  The module has been stable for so long I wasn't sure if I would have to fork but glad I didn't have to.
